### ISSUE TITLE
Could you give me a jstree action demo?

### ISSUE THREAD

**Issue by myidcn** [alexandernst/jstree-actions#12]
Hi Alexander，

It is my pleasure to write here for you.
I write a html UI with jstree recently.
But I can not use the jstree-actions plugin correctly,
I need you help kindly, 
Could you give me a jstree action demo?
Many thanks for your support. 

Yours faithfully,

**Comment by alexandernst** [comment]
http://jsfiddle.net/1m97d73f/9/

**Comment by myidcn** [comment]
hi，
thank you for reply 
I have test the demo in local machine, but it could not wrok.
Could you give me a zip file demo. 
my mail is yufeng869@163.com. 
thank you very much.
