### ISSUE TITLE
onclick isnt giving out the original mouse event

### ISSUE THREAD

**Issue by mikila85** [alexandernst/jstree-actions#13]
currently:
`action_el.onclick = function() {
				var node = self.get_node(action_el);
				action.callback(node_id, node, action_id, action_el);
			};`

i suggest doing:

`action_el.onclick = function(e) {
				var node = self.get_node(action_el);
				action.callback(node_id, node, action_id, action_el, e);
			};`

**Comment by alexandernst** [comment]
Since this is not going to break the api signature for older versions, I can merge a patch and release asap (if you're willing to send a patch). 👍

**Comment by mikila85** [comment]
[Pull Request](https://github.com/alexandernst/jstree-actions/pull/14)

**Comment by mikila85** [comment]
Hi, can you create a new release so we can use it?

**Comment by mikila85** [comment]
got it by using `yarn add alexandernst/jstree-actions` just got it straight from github

**Comment by emoryy** [comment]
@alexandernst 
It would still be nice to get a new release with this. I needlessly spent a significant amount time by debugging why I don't get the event despite the source code here in github showing otherwise.

**Comment by alexandernst** [comment]
You're absolutely right! I'm releasing it right now

**Comment by alexandernst** [comment]
@emoryy Published!

**Comment by emoryy** [comment]
@alexandernst Thank you!
